-- See https://github.com/femga/rdr3_discoveries/blob/f729ba03f75a591ce5c841642dc873345242f612/weapons/weapons.lua for more information.

---@type NssLibsServerConfigValidatorWeaponsRaw
NssLibsServerConfigValidatorWeaponsConfig = {
    'weapon_melee_knife_jawbone',
    'weapon_melee_machete',
    'weapon_melee_torch',
    'weapon_melee_knife',
    'weapon_pistol_volcanic',
    'weapon_pistol_m1899',
    'weapon_pistol_semiauto',
    'weapon_pistol_mauser',
    'weapon_repeater_evans',
    'weapon_repeater_henry',
    'weapon_repeater_winchester',
    'weapon_repeater_carbine',
    'weapon_revolver_doubleaction',
    'weapon_revolver_cattleman',
    'weapon_revolver_cattleman_mexican',
    'weapon_revolver_lemat',
    'weapon_revolver_schofield',
    'weapon_revolver_doubleaction_gambler',
    'weapon_rifle_springfield',
    'weapon_rifle_boltaction',
    'weapon_rifle_varmint',
    'weapon_shotgun_sawedoff',
    'weapon_shotgun_doublebarrel_exotic',
    'weapon_shotgun_pump',
    'weapon_shotgun_repeating',
    'weapon_shotgun_semiauto',
    'weapon_shotgun_doublebarrel',
    'weapon_sniperrifle_carcano',
    'weapon_sniperrifle_rollingblock',
    'weapon_melee_hatchet',
    'weapon_melee_hatchet_hunter',
    'weapon_thrown_molotov',
    'weapon_thrown_tomahawk_ancient',
    'weapon_thrown_tomahawk',
    'weapon_thrown_dynamite',
    'weapon_melee_hatchet_double_bit',
    'weapon_thrown_throwing_knives',
    'weapon_melee_cleaver',
    'weapon_melee_davy_lantern',
    'weapon_kit_binoculars',
    'weapon_kit_camera',
    'weapon_bow',
    'weapon_fishingrod',
    'weapon_lasso',

    -- Weapons from game version 1207.80 till 1311.12
    'weapon_kit_camera_advanced',
    'weapon_melee_machete_horror',
    'weapon_bow_improved',
    'weapon_rifle_elephant',
    'weapon_revolver_navy',
    'weapon_lasso_reinforced',
    'weapon_kit_binoculars_improved',
    'weapon_melee_knife_trader',
    'weapon_melee_machete_collector',
    'weapon_moonshinejug_mp',
    'weapon_thrown_bolas',
    'weapon_thrown_poisonbottle',

    -- Weapons from game version 1311.12 till 1355.18
    'weapon_kit_metal_detector',
    'weapon_revolver_navy_crossover',
    'weapon_thrown_bolas_hawkmoth',
    'weapon_thrown_bolas_ironspiked',
    'weapon_thrown_bolas_intertwined',

    -- Weapons from game version 1355.18 till 1436.26
    'weapon_melee_knife_horror',
    'weapon_melee_knife_rustic',
    'weapon_melee_lantern_halloween',
}